regions:
    activities:
        url: '/Person/api/collection/ActivityStream/all/10/0/{"display_date":-1}'
        args: []
        partial: 'Person/collections/activity.hbs'
        type: 'Collection'
